### ISSUE TITLE
Tainted Storm Focus crash

### ISSUE THREAD

**Issue by Dayyer1** [yorkeJohn/Tainted-Magic#48] opened 2017-07-26 04:49 UTC
I crashed when trying to equip the Tainted Storm Focus.

[crash-2017-07-25_22.44.28-client.txt](https://github.com/yorkeJohn/Tainted-Magic/files/1175492/crash-2017-07-25_22.44.28-client.txt)

**Comment by Dayyer1** [comment] 2017-07-27 05:14
Sort of figured it out... when I looked at the focus in my inventory, it said "Unnamed". This has happened with other foci when I update a Thaumcraft-related mod--a focus can become "Unnamed" and then crash the game when you try to equip it. It also happened with the Vis Shards focus.
It's not fixed, though, so I won't close the issue yet.
Btw- the new Dark Matter upgrade?
NICE.

**Comment by Dayyer1** [comment] 2017-07-27 05:16
...and, the Bloodlust upgrade texture is not showing correctly in the focal manipulator.

**Comment by yorkeJohn** [comment] 2017-07-27 17:41
I'm releasing a patch today. Let's see if you can reproduce the issue after the update.

**Comment by Dayyer1** [comment] 2017-07-27 23:43
Ok. Will the patch be on curseforge?

**Comment by Dayyer1** [comment] 2017-07-27 23:44
Nevermind. Silly question.

**Comment by yorkeJohn** [comment] 2017-07-28 00:21
Where else would it be?

**Comment by yorkeJohn** [comment] 2017-07-28 02:26
I fixed the Bloodlust icon - the path was wrong. The other issue isn't a Tainted Magic issue (I don't think?). We can close this issue once we're sure.

**Comment by yorkeJohn** [comment] 2017-07-28 17:32
So I think this was just a problem with the ID change of the Tainted Shockwave and Dark Matter foci. I'm going to close this issue since the only way to fix this is to throw away the 'unnamed' foci.

**Closed as completed by yorkeJohn** 2017-07-28 17:32 UTC
