### ISSUE TITLE
Trying to change wand focus crashes game client-side

### ISSUE THREAD

**Issue by Crashcraft** [yorkeJohn/Tainted-Magic#49] opened 2017-07-28 04:01 UTC
I know it says Thaumcraft, but I only get this error when I updated Tainted Magic to the most current version (r7.8; happened on r7.7 too).
-----------------------------------------------------------------------------------------------------------
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/27/17 8:48 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at thaumcraft.api.wands.ItemFocusBasic.addFocusInformation(ItemFocusBasic.java:73)
	at thaumcraft.api.wands.ItemFocusBasic.func_77624_a(ItemFocusBasic.java:58)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at thaumcraft.client.lib.REHWandHandler.renderFocusRadialHUD(REHWandHandler.java:303)
	at thaumcraft.client.lib.REHWandHandler.handleFociRadial(REHWandHandler.java:140)
	at thaumcraft.client.lib.RenderEventHandler.renderOverlay(RenderEventHandler.java:100)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_123_RenderEventHandler_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1362)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.api.wands.ItemFocusBasic.addFocusInformation(ItemFocusBasic.java:73)
	at thaumcraft.api.wands.ItemFocusBasic.func_77624_a(ItemFocusBasic.java:58)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at thaumcraft.client.lib.REHWandHandler.renderFocusRadialHUD(REHWandHandler.java:303)
	at thaumcraft.client.lib.REHWandHandler.handleFociRadial(REHWandHandler.java:140)
	at thaumcraft.client.lib.RenderEventHandler.renderOverlay(RenderEventHandler.java:100)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_123_RenderEventHandler_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1362)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['MinecraftUser'/360, l='MpServer', x=834.75, y=76.62, z=845.08]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (31,64,-61), Chunk: (at 15,4,3 in 1,-4; contains blocks 16,0,-64 to 31,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 12716682 game time, 766398 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntitySpider['Spider'/529, l='MpServer', x=860.91, y=27.00, z=814.03], EntitySkeleton['Skeleton'/530, l='MpServer', x=855.69, y=27.00, z=808.78], EntityBat['Bat'/531, l='MpServer', x=865.75, y=27.00, z=817.19], EntityZombie['Zombie'/536, l='MpServer', x=864.31, y=27.00, z=813.31], EntitySpider['Spider'/537, l='MpServer', x=862.59, y=27.00, z=815.09], EntityCreeper['Creeper'/538, l='MpServer', x=871.31, y=15.00, z=865.50], EntityBat['Bat'/539, l='MpServer', x=874.78, y=26.00, z=893.75], EntityBat['Bat'/542, l='MpServer', x=886.25, y=26.00, z=795.50], EntityCreeper['Creeper'/543, l='MpServer', x=882.30, y=16.39, z=867.70], EntityZombie['Zombie'/548, l='MpServer', x=907.03, y=12.00, z=822.44], EntityBat['Bat'/549, l='MpServer', x=907.56, y=23.00, z=836.53], EntitySkeleton['Skeleton'/550, l='MpServer', x=910.50, y=30.00, z=835.50], EntityZombie['Zombie'/551, l='MpServer', x=906.91, y=26.00, z=838.34], EntitySkeleton['Skeleton'/552, l='MpServer', x=909.47, y=30.00, z=879.09], EntityZombie['Zombie'/565, l='MpServer', x=913.50, y=26.00, z=855.50], EntityCreeper['Creeper'/569, l='MpServer', x=914.50, y=23.00, z=889.50], EntityClientPlayerMP['MinecraftUser'/360, l='MpServer', x=834.75, y=76.62, z=845.08], EntityBat['Bat'/424, l='MpServer', x=765.41, y=23.00, z=829.25], EntityBat['Bat'/425, l='MpServer', x=767.81, y=23.00, z=826.75], EntityMinecartChest['entity.MinecartChest.name'/426, l='MpServer', x=763.50, y=17.50, z=897.50], EntityCreeper['Creeper'/428, l='MpServer', x=756.50, y=21.00, z=924.50], EntityZombie['Zombie'/436, l='MpServer', x=783.50, y=16.00, z=773.50], EntityZombie['Zombie'/437, l='MpServer', x=768.41, y=29.00, z=830.91], EntityCreeper['Creeper'/438, l='MpServer', x=777.97, y=16.00, z=913.38], EntityZombie['Zombie'/451, l='MpServer', x=787.50, y=16.00, z=774.50], EntityZombie['Zombie'/452, l='MpServer', x=786.53, y=16.00, z=877.09], EntityCreeper['Creeper'/453, l='MpServer', x=790.50, y=17.00, z=872.09], EntitySpider['Spider'/454, l='MpServer', x=790.50, y=17.00, z=874.00], EntitySquid['Squid'/455, l='MpServer', x=795.22, y=52.38, z=900.03], EntitySkeleton['Skeleton'/461, l='MpServer', x=808.06, y=35.00, z=768.50], EntityDart['Golem Dart'/462, l='MpServer', x=812.50, y=63.06, z=806.00], EntityBat['Bat'/463, l='MpServer', x=812.63, y=27.10, z=836.75], EntityBat['Bat'/464, l='MpServer', x=802.63, y=33.10, z=837.13], EntityBat['Bat'/465, l='MpServer', x=802.53, y=33.10, z=837.81], EntityMinecartChest['entity.MinecartChest.name'/466, l='MpServer', x=804.50, y=16.34, z=910.50], EntityZombie['Zombie'/467, l='MpServer', x=801.97, y=12.00, z=917.59], EntitySkeleton['Skeleton'/468, l='MpServer', x=809.34, y=12.00, z=924.09], EntitySkeleton['Skeleton'/469, l='MpServer', x=806.88, y=18.00, z=914.53], EntityCreeper['Creeper'/478, l='MpServer', x=830.50, y=27.00, z=830.50], EntitySkeleton['Skeleton'/479, l='MpServer', x=822.22, y=27.00, z=830.50], EntitySelfShearingSheep['Self-Shearing Sheep'/480, l='MpServer', x=822.33, y=63.00, z=856.63], EntitySelfShearingSheep['Self-Shearing Sheep'/481, l='MpServer', x=823.55, y=63.00, z=855.50], EntitySelfShearingSheep['Self-Shearing Sheep'/482, l='MpServer', x=823.31, y=63.00, z=858.22], EntitySelfShearingSheep['Self-Shearing Sheep'/483, l='MpServer', x=821.92, y=63.00, z=855.45], EntitySquid['Squid'/484, l='MpServer', x=822.81, y=50.00, z=895.72], EntitySkeleton['Skeleton'/485, l='MpServer', x=827.94, y=17.00, z=903.56], EntityCreeper['Creeper'/492, l='MpServer', x=843.50, y=27.00, z=814.50], EntityDart['Golem Dart'/493, l='MpServer', x=847.78, y=66.38, z=811.00], EntityCreeper['Creeper'/494, l='MpServer', x=844.56, y=27.00, z=818.84], EntityCreeper['Creeper'/495, l='MpServer', x=846.75, y=27.00, z=817.31], EntityCreeper['Creeper'/496, l='MpServer', x=845.22, y=27.00, z=819.69], ThePrinceAdult['The Young Adult Prince'/497, l='MpServer', x=833.84, y=87.00, z=830.66], EntityCreeper['Creeper'/498, l='MpServer', x=844.00, y=19.00, z=882.44], EntityBat['Bat'/499, l='MpServer', x=842.66, y=16.00, z=905.28], EntitySkeleton['Skeleton'/500, l='MpServer', x=832.50, y=16.00, z=903.50], EntityZombie['Zombie'/501, l='MpServer', x=842.03, y=16.00, z=905.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 656395840 bytes (625 MB) / 1407582208 bytes (1342 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 Optifine OptiFine_1.7.10_HD_U_D3 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	ThE-core{0.10.0.0} [Thaumic Energistics Core] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2a} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2a.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.32_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.32_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.424_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.424_beta.jar) 
	UCHIJAAAA	extracells{2.3.9} [Extra Cells 2] (ExtraCells-1.7.10-2.3.9b188.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-512.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.574} [Forbidden Magic] (Forbidden Magic-1.7.10-0.574.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-121.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	TaintedMagic{r7.8} [Tainted Magic] (Tainted-Magic-r7.8.jar) 
	UCHIJAAAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UCHIJAAAA	thaumicenergistics{1.0.0.1} [Thaumic Energistics] (thaumicenergistics-1.0.0.1.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	ThermalDynamics: -[1.7.10]1.2.1-172
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-5.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [HEE Music v1.0.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTX 770/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by yorkeJohn** [comment] 2017-07-28 13:26
What focus were you trying to equip? Also please put crash reports in a gist or a text file.

**Comment by Crashcraft** [comment] 2017-07-28 15:58
I apologize, I'm new to using Github, but thank you for telling me. I could provide a list of all the wand foci I have, but I recently discovered something that I had missed before: upon opening my bottomless pouch (Thaumic Tinkerer), I noticed that when switching from r7.6 to r7.8, while the Dark Matter and Tainted Shockwave foci were removed, the Vis Shard and Tainted Storm foci were not, and were, for some reason, changed to 'Unnamed.' After deleting those and replacing them, everything's working fine. I apologize for not realizing this sooner, but could this possibly be a bug?

**Comment by yorkeJohn** [comment] 2017-07-28 16:18
Okay, please refer to #48 
I believe this is caused by the change of item ID for the Tainted Shockwave and the Dark Matter foci... they were the only two whose IDs were changed and coincidentally the two that were 'unnamed'. I think this is just the way Thaumcraft handles foci and their corresponding item IDs. I'm going to close this issue since #48 seems to be the same problem.

**Closed as completed by yorkeJohn** 2017-07-28 16:18 UTC
